### ISSUE TITLE
安装pont插件后，底部的status bar 并没有多出按钮

### ISSUE THREAD

**Issue by zmzimpl** [nefe/pont#16]
![image](https://user-images.githubusercontent.com/27490895/53229717-f8109300-36bf-11e9-8e97-f32c01929222.png)
请问是不是我哪里理解错了？

**Comment by jasonHzq** [comment]
有reload过IDE吗？

**Comment by zmzimpl** [comment]
> 有reload过IDE吗？

有的，pont重装过，并重启了，看了下，VS code的控制台报了以下错误
![image](https://user-images.githubusercontent.com/27490895/53230438-a23cea80-36c1-11e9-9f02-b2f4c8adb07a.png)

**Comment by jasonHzq** [comment]
应该是 windows 用户的兼容性问题。周末找个 windows 电脑 DEBUG 一下。

**Comment by jasonHzq** [comment]
已修复
