### ISSUE TITLE
你好 能提供一个可用方案吗

### ISSUE THREAD

**Issue by yzStrive** [nefe/pont#4]
我暂时没发现怎么用起来，好像vscode插件的文档也没完善。

**Comment by jasonHzq** [comment]
感谢提醒，我已在文档添加了[pont-demo](https://github.com/nefe/pont)的示例链接。并且在 vscode-pont 文档中添加了 pont 的链接。

**Comment by yzStrive** [comment]
有没有考虑提供cli来生成？不是很想依赖vscode
