### ISSUE TITLE
讨论： 获取远程数据成功后应该加一些规范化处理，比如 包括中文、空格、中横线的基类名称

### ISSUE THREAD

**Issue by gaoletian** [nefe/pont#9]
![image](https://user-images.githubusercontent.com/25849581/53005893-2186b000-346f-11e9-8f39-75712b1f8a1b.png)

**Comment by jasonHzq** [comment]
可以展开说一下具体情况吗？基类对应的是后端 class 名字，后端把 class 名字起为了中文？

**Comment by gaoletian** [comment]
在swagger.josn 的 definitions 里的类名有各种奇葩问题，我列举几种类的命名

"banner参数返回数据"
"查询账户余额Vo"
"提现失败 获取可重新绑定银行卡列表的请求数据"

**Comment by jasonHzq** [comment]
我觉得可以让你们 java 取消这个汉化，我们在 Pont 在使用上，也会和后端约定一定的规范。

**Comment by jasonHzq** [comment]
如果 Pont 去做汉字翻译成英文，然后改成 camelCase，我觉得会比较奇怪。

**Comment by gaoletian** [comment]
工具就应该具有普适性吧，如果有历史原因，再让java去改的话不太可能了。而作为工具，至少做为可选功能，应该为用户提供一个解决方案

**Comment by jasonHzq** [comment]
已经修复
